---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: chatbot-app-build
  labels:
    backstage.io/kubernetes-id: chatbot-app
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master,main]"
    pipelinesascode.tekton.dev/task: "https://raw.githubusercontent.com/tektoncd/catalog/refs/heads/main/task/git-clone/0.10/git-clone.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/tektoncd/catalog/refs/heads/main/task/maven/0.4/maven.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/tektoncd/catalog/refs/heads/main/task/buildah/0.9/buildah.yaml"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: source-repo
      value: "{{ repo_url }}"
    - name: source-branch
      value: "{{ revision }}"
    - name: output-image
      value: "quay-d589v.apps.cluster-d589v.d589v.sandbox657.opentlc.com/quayadmin/chatbot-app"
    - name: sonarqube-host-url
      value: https://sonarqube-sonarqube.apps.cluster-d589v.d589v.sandbox657.opentlc.com
    - name: sonarqube-project-key
      value: chatbot-app
    - name: sonarqube-project-secret
      value: chatbot-app-sonarqube-secret
    - name: cyclonedx-host-url
      value: https://cyclonedx-bom-repo-server-cyclonedx.apps.cluster-d589v.d589v.sandbox657.opentlc.com
    - name: stackrox-endpoint
      value: central-stackrox.apps.cluster-d589v.d589v.sandbox657.opentlc.com:443
    - name: stackrox-secret
      value: chatbot-app-stackrox-token
    - name: git-host
      value: gitlab-gitlab.apps.cluster-d589v.d589v.sandbox657.opentlc.com
    - name: git-owner
      value: development
    - name: component-id
      value: chatbot-app
    - name: common-password-secret
      value: common-password-secret
    - name: rekor-url
      value: http://rekor-server.trusted-artifact-signer.svc
    - name: tuf-mirror
      value: http://tuf.trusted-artifact-signer.svc
    - name: certificate-identity
      value: $(tt.params.git-committer)
    - name: oidc-issuer
      value: https://keycloak-rhsso.apps.cluster-d589v.d589v.sandbox657.opentlc.com/auth/realms/openshift
    - name: maven-image
      value: registry.redhat.io/ubi9/openjdk-21
  pipelineSpec:
    params:
      - name: source-repo
        description: source repo that contains the application code
        type: string
      - name: source-branch
        description: source branch to build from
        type: string
      - name: output-image
        description: reference of the image that will get created
        type: string
      - name: sonarqube-host-url
        type: string
      - name: sonarqube-project-key
        type: string
      - name: sonarqube-project-secret
        type: string
      - name: cyclonedx-host-url
        type: string
      - name: stackrox-endpoint
        type: string
      - name: stackrox-secret
        type: string
      - name: git-host
        type: string
      - name: git-owner
        type: string
      - name: component-id
        type: string
      - name: common-password-secret
        type: string
      - name: rekor-url
        type: string
      - name: tuf-mirror
        type: string
      - name: certificate-identity
        type: string
      - name: oidc-issuer
        type: string
      - name: maven-image
        type: string
    tasks:
      - name: git-clone
        params:
          - name: url
            value: $(params.source-repo)
          - name: revision
            value: $(params.source-branch)
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source-folder
      - name: package
        runAfter:
          - git-clone
        params:
          - name: MAVEN_IMAGE
            value: $(params.maven-image)
        taskRef:
          name: maven
        workspaces:
          - name: source
            workspace: source-folder
          - name: maven-settings
            workspace: maven-settings
      - name: scan-source
        params:
          - name: sonarqubeHostUrl
            value: $(params.sonarqube-host-url)
          - name: sonarqubeProjectKey
            value: $(params.sonarqube-project-key)
          - name: sonarqubeProjectSecret
            value: $(params.sonarqube-project-secret)
        runAfter:
          - package
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: scan-code
            - name: namespace
              value: chatbot-app-dev
        workspaces:
          - name: repository
            workspace: source-folder
      - name: build-sign-image
        params:
          - name: IMAGE
            value: $(params.output-image)
        runAfter:
          - scan-source
        taskRef:
          name: buildah
        workspaces:
          - name: source
            workspace: source-folder
      - name: upload-sbom-to-tpa
        runAfter:
          - build-sign-image
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: upload-sbom-to-tpa
            - name: namespace
              value: chatbot-app-dev
        params:
          - name: COMPONENT_ID
            value: $(params.component-id)
        workspaces:
          - name: sboms
            workspace: source-folder
      - name: upload-sbom-to-cyclonedx-repo
        params:
          - name: cyclonedxHostUrl
            value: $(params.cyclonedx-host-url)
          - name: image
            value: $(params.output-image)@$(tasks.build-sign-image.results.IMAGE_DIGEST)
        runAfter:
          - build-sign-image
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: upload-sbom-to-cyclonedx-repo
            - name: namespace
              value: chatbot-app-dev
        workspaces:
          - name: repository
            workspace: source-folder
      - name: acs-image-check
        params:
          - name: rox_central_endpoint
            value: $(params.stackrox-endpoint)
          - name: rox_api_token
            value: $(params.stackrox-secret)
          - name: image
            value: $(params.output-image)
          - name: insecure-skip-tls-verify
            value: "true"
          - name: image_digest
            value: $(tasks.build-sign-image.results.IMAGE_DIGEST)
        runAfter:
          - upload-sbom-to-tpa
          - upload-sbom-to-cyclonedx-repo
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: acs-image-check
            - name: namespace
              value: chatbot-app-dev
        workspaces:
          - name: reports
            workspace: reports
      - name: acs-image-scan
        params:
          - name: rox_central_endpoint
            value: $(params.stackrox-endpoint)
          - name: rox_api_token
            value: $(params.stackrox-secret)
          - name: image
            value: $(params.output-image)
          - name: insecure-skip-tls-verify
            value: "true"
          - name: image_digest
            value: $(tasks.build-sign-image.results.IMAGE_DIGEST)
        runAfter:
          - upload-sbom-to-tpa
          - upload-sbom-to-cyclonedx-repo
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: acs-image-scan
            - name: namespace
              value: chatbot-app-dev
        workspaces:
          - name: reports
            workspace: reports
      - name: acs-deploy-check
        params:
          - name: rox_central_endpoint
            value: $(params.stackrox-endpoint)
          - name: rox_api_token
            value: $(params.stackrox-secret)
          - name: git_host
            value: $(params.git-host)
          - name: git_owner
            value: $(params.git-owner)
          - name: component_id
            value: $(params.component-id)
          - name: common_password_secret
            value: $(params.common-password-secret)
          - name: insecure-skip-tls-verify
            value: "true"
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: acs-deploy-check
            - name: namespace
              value: chatbot-app-dev
        runAfter:
          - upload-sbom-to-tpa
          - upload-sbom-to-cyclonedx-repo
        workspaces:
          - name: reports
            workspace: reports
      - name: query-rekor-signed-provenance
        params:
          - name: imageDigest
            value: $(tasks.build-sign-image.results.IMAGE_DIGEST)
          - name: rekorUrl
            value: $(params.rekor-url)
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: rekor-signed-provenance
            - name: namespace
              value: chatbot-app-dev
        runAfter:
          - acs-image-check
          - acs-image-scan
          - acs-deploy-check
      - name: resync
        params:
          - name: COMPONENT_ID
            value: $(params.component-id)
        runAfter:
          - query-rekor-signed-provenance
        taskRef:
          resolver: cluster
          params:
            - name: kind
              value: task
            - name: name
              value: resync
            - name: namespace
              value: chatbot-app-dev
    results:
      - name: IMAGE_URL
        value: "$(tasks.build-sign-image.results.IMAGE_URL)"
      - name: IMAGE_DIGEST
        value: "$(tasks.build-sign-image.results.IMAGE_DIGEST)"
      - name: CHAINS-GIT_URL
        value: "$(tasks.git-clone.results.url)"
      - name: CHAINS-GIT_COMMIT
        value: "$(tasks.git-clone.results.commit)"
      - name: ACS_SCAN_OUTPUT
        value: "$(tasks.acs-image-scan.results.SCAN_OUTPUT)"
    workspaces:
      - name: source-folder
      - name: maven-settings
      - name: docker-config
      - name: reports
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: maven-settings
      emptyDir: {}
    - name: docker-config
      emptyDir: {}
    - name: reports
      emptyDir: {}
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
